name: XIV Rus Dev

project:
  description: Неофициальная русская локализация FINAL FANTASY XIV
  download_url: https://xivrus.ru/download
  download_text: Скачать

plugins:
  - jekyll-remote-theme

ui:
  mode: 'dark' # 'auto', 'dark', 'light'

# Build settings
remote_theme: xivrus/xivrus-theme
markdown: kramdown
kramdown:
  parse_block_html: true
